---
name: ci
on:
  push:
    branches:
      - master
      - 'release**'
      - 'debug/**'
  pull_request: ~

permissions:
  contents: read
  id-token: write

env:
  AWS_DEFAULT_REGION:    ${{ secrets.AWS_REGION }}

jobs:
  manifest:
    if: ${{ github.event_name == 'push' }}
    name: Artifacts manifest
    runs-on:
      - baremetal

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.ASSURIODEV_OIDC_AWS_ROLE_ARN }}

      - name: Make manifest
        run: echo '926' > latest && cat latest | grep -E '^[0-9]+$'

      - name: Upload manifest
        run: |
          branch=master
          if ! [[ ${branch} =~ ^release ]] && ! [[ ${branch} =~ ^master ]]; then
            tag="--tag elastio:dev=true"
          fi
          repobuild/upload.sh \
            --source latest \
            --bucket artifacts.assur.io \
            --target /linux/elastio-snap/$branch \
            ${tag}

  dispatch-packaging-repo:
    if: ${{ github.event_name == 'push' }}
    name: Trigger repo upload
    needs: manifest
    runs-on:
      - baremetal

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Dispatch packaging repo
        env:
          REPO_HOOK_TOKEN: ${{ secrets.REPO_HOOK_TOKEN }}
        run: .github/scripts/dispatch_packaging.sh
